export const COLLECTION_SAVE_SUCCESS = "COLLECTION_SAVE_SUCCESS";
export const COLLECTION_SAVE_FAIL = "COLLECTION_SAVE_FAIL";
export const COLLECTION_SAVE_REQUEST = 'COLLECTION_SAVE_REQUEST';

export const COLLECTION_LIST_SUCCESS = "COLLECTION_LIST_SUCCESS";
export const COLLECTION_LIST_FAIL = "COLLECTION_LIST_FAIL";
export const COLLECTION_LIST_REQUEST = 'COLLECTION_LIST_REQUEST';
export const COLLECTION_DETAIL_SUCCESS = "COLLECTION_DETAIL_SUCCESS";
export const COLLECTION_DETAIL_FAIL = "COLLECTION_DETAIL_FAIL";
export const COLLECTION_DETAIL_REQUEST = 'COLLECTION_DETAIL_REQUEST';


export const COLLECTION_REMOVE_REQUEST = "COLLECTION_REMOVE_REQUEST";
export const COLLECTION_REMOVE_SUCCESS = "COLLECTION_REMOVE_SUCCESS";
export const COLLECTION_REMOVE_FAIL = "COLLECTION_REMOVE_FAIL";
export const COLLECTION_REMOVE_SUCCESS_FALSE='COLLECTION_REMOVE_SUCCESS_FALSE'


export const SUBMETER_SAVE_REQUEST = "SUBMETER_SAVE_REQUEST";
export const SUBMETER_SAVE_SUCCESS = "SUBMETER_SAVE_SUCCESS";
export const SUBMETER_SAVE_FAIL = "SUBMETER_SAVE_FAIL";

export const SUBMETER_REMOVE_REQUEST = "SUBMETER_REMOVE_REQUEST";
export const SUBMETER_REMOVE_SUCCESS = "SUBMETER_REMOVE_SUCCESS";
export const SUBMETER_REMOVE_FAIL = "SUBMETER_REMOVE_FAIL";
export const SUBMETER_REMOVE_SUCCESS_FALSE='SUBMETER_REMOVE_SUCCESS_FALSE'

export const READINGS_SAVE_REQUEST = "READINGS_SAVE_REQUEST";
export const READINGS_SAVE_SUCCESS = "READINGS_SAVE_SUCCESS";
export const READINGS_SAVE_FAIL = "READINGS_SAVE_FAIL";

export const READINGSLIST_LOAD_REQUEST = "READINGSLIST_LOAD_REQUEST";
export const READINGSLIST_LOAD_SUCCESS = "READINGSLIST_LOAD_SUCCESS";
export const READINGSLIST_LOAD_FAIL = "READINGSLIST_LOAD_FAIL";


export const SUBMETER_LIST_SUCCESS = "SUBMETER_LIST_SUCCESS";
export const SUBMETER_LIST_FAIL = "SUBMETER_LIST_FAIL";
export const SUBMETER_LIST_REQUEST = 'SUBMETER_LIST_REQUEST';

export const SUBMETER_CLEAR_LIST = "SUBMETER_CLEAR_LIST";


export const READINGS_REMOVE_REQUEST = "READINGS_REMOVE_REQUEST";
export const READINGS_REMOVE_SUCCESS = "READINGS_REMOVE_SUCCESS";
export const READINGS_REMOVE_FAIL = "READINGS_REMOVE_FAIL";
export const READINGS_REMOVE_SUCCESS_FALSE='READINGS_REMOVE_SUCCESS_FALSE'
