export const COLLECTION_SAVE_SUCCESS = "COLLECTION_SAVE_SUCCESS";
export const COLLECTION_SAVE_FAIL = "COLLECTION_SAVE_FAIL";
export const COLLECTION_SAVE_REQUEST = 'COLLECTION_SAVE_REQUEST';

export const COLLECTION_LIST_SUCCESS = "COLLECTION_LIST_SUCCESS";
export const COLLECTION_LIST_FAIL = "COLLECTION_LIST_FAIL";
export const COLLECTION_LIST_REQUEST = 'COLLECTION_LIST_REQUEST';

export const COLLECTION_DETAIL_SUCCESS = "COLLECTION_DETAIL_SUCCESS";
export const COLLECTION_DETAIL_FAIL = "COLLECTION_DETAIL_FAIL";
export const COLLECTION_DETAIL_REQUEST = 'COLLECTION_DETAIL_REQUEST';

export const SUBMETER_SAVE_REQUEST = "SUBMETER_SAVE_REQUEST";
export const SUBMETER_SAVE_SUCCESS = "SUBMETER_SAVE_SUCCESS";
export const SUBMETER_SAVE_FAIL = "SUBMETER_SAVE_FAIL";


export const SUBMETER_LIST_SUCCESS = "SUBMETER_LIST_SUCCESS";
export const SUBMETER_LIST_FAIL = "SUBMETER_LIST_FAIL";
export const SUBMETER_LIST_REQUEST = 'SUBMETER_LIST_REQUEST';

export const SUBMETER_CLEAR_LIST = "SUBMETER_CLEAR_LIST";
