export const CLOSE_CREATE_COLLECTION='CLOSE_CREATE_COLLECTION';
export const OPEN_CREATE_COLLECTION='OPEN_CREATE_COLLECTION';

export const CLOSE_CREATE_SUBMETER='CLOSE_CREATE_SUBMETER';
export const OPEN_CREATE_SUBMETER='OPEN_CREATE_SUBMETER';
